# solution for delay of ESC in vim
# https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed
set -sg escape-time 10

# rebind the prefix to C-a
unbind C-a
set -g prefix C-a
bind C-a send-prefix

set -g mouse on


# increase history from 2000 (default) to 5000
set-option -g history-limit 5000


# default split pane shortcuts Prefix + % and Prefix + "
# are not intuitive
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# switch panes using prefix + hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
